name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user
        run: |
          git config --global user.email "dinesh.radjou@etu.univ-amu.fr"
          git config --global user.name "Dinesh Rajdou"

      - name: Copy public folder to root
        run: |
          # Create the gh-pages branch if it doesn't exist
          git fetch origin gh-pages || git checkout --orphan gh-pages
          # Copy the contents of the public folder into the root of the repository
          cp -r public/* .
          # Add all files
          git add .
          git commit -m "Deploy static site from public/"

      - name: Push changes to gh-pages branch
        run: |
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/RADJOU-Dinesh-24003262/TechNews-IUT.git gh-pages
