name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Branche à surveiller (change si tu utilises 'master' ou une autre branche)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Récupère le code du dépôt

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'  # Remplace par la version de Hugo que tu utilises

      - name: Build the site
        run: |
          hugo  # Cela va générer ton site dans le dossier public/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub génère ce token automatiquement
          publish_dir: ./public  # C'est ici que Hugo génère ton site statique
